name: Android CI

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Download and setup Android SDK
      run: |
        sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools
        sudo wget -q https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O /tmp/tools.zip
        sudo unzip -q /tmp/tools.zip -d /usr/local/lib/android/sdk/cmdline-tools
        sudo mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools/tools
        echo "sdkmanager --version"
        yes | /usr/local/lib/android/sdk/cmdline-tools/tools/bin/sdkmanager --licenses
        /usr/local/lib/android/sdk/cmdline-tools/tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3"
    
    - name: Build with Gradle
      run: ./gradlew build
